title: Delta OA UI
email: hyram.tang@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Source
source: docs                  #Jekyll 读取文件的路径。
destination: _gh_pages        #Jekyll 写入文件的路径。
encoding: UTF-8               #设置文件的编码，仅 Ruby 1.9 以上可用。2.0.0　版本以后默认值为 utf-8，之前版本默认值为 nil，使用 Ruby 默认的 ASCII-8BIT。可以用命令 ruby -e 'puts Encoding::list.join("\n")' 查看 Ruby 可用的编码。
#safe: false                   #禁用 自定义插件。
#exclude: [DIR, FILE, ...]    #转换时排除某些文件、文件夹。
#include: [DIR, FILE, ...]    #转换时强制包含某些文件、文件夹。
#keep_files: [DIR, FILE, ...] #当生成站点时，保留选择的文件。对文件不是由 jekyll 生成是有用的。例如由你的构建工具生成的文件或者资源。路径是相对于 destination。
#timezone: TIMEZONE           #设置时区，这个设置作用于 TZ 变量， Ruby 用它来处理日期和时间。 IANA Time Zone Database 里边的都有效，比如 America/New_York 。默认值为操作系统的时区。

# Serve
host: 127.0.0.1               #主机 ip/名称
port: 9002                    #端口
baseurl: ""                   #网站的根路径
url: ""                       # the base hostname & protocol for your site, e.g. http://example.com
